import type {
  LeadRow, LeadDetail, OutreachDraft, ProposalDocument, ResponseRecord,
  CRMLead, FunnelMetrics, DashboardLeadRow, FollowUpLead, CategoryInsight,
  ModelStatus, DiscoveryReport,
} from './types';

export const mockLeads: LeadRow[] = [
  {
    place_id: 'node/123456',
    name: 'Cafe Mocha',
    category: 'restaurant',
    website: 'https://cafemocha.com',
    phone: '+255123456789',
    address: '123 Main St, Dar es Salaam',
    lead_score: 72,
    priority: 'High',
    problems: ['No online ordering capability', 'Website not mobile-friendly'],
    solutions: ['Online ordering platform', 'Mobile website redesign'],
    potential_value: 'High',
    total_qualification_score: 68,
    pipeline_status: 'Contacted',
    discovered_at: '2026-09-01T10:30:00Z',
    latitude: -6.7924,
    longitude: 39.2083,
  },
  {
    place_id: 'node/234567',
    name: 'Hotel Palm Resort',
    category: 'hotel',
    website: 'https://hotelpalm.co.tz',
    phone: '+255765432100',
    address: 'Beach Road, Dar es Salaam',
    lead_score: 85,
    priority: 'High',
    problems: ['No online booking system', 'No review management', 'Outdated website design'],
    solutions: ['Hotel booking platform', 'Review management dashboard', 'Website modernization'],
    potential_value: 'High',
    total_qualification_score: 82,
    pipeline_status: 'Warm',
    discovered_at: '2026-09-01T10:35:00Z',
    latitude: -6.7749,
    longitude: 39.2244,
  },
  {
    place_id: 'node/345678',
    name: 'City Secondary School',
    category: 'school',
    website: null,
    phone: '+255222334455',
    address: 'Education District, Mwanza',
    lead_score: 78,
    priority: 'High',
    problems: ['No website found', 'No student portal', 'No fee payment system'],
    solutions: ['School management platform', 'Student portal', 'Online fee payment'],
    potential_value: 'High',
    total_qualification_score: 71,
    pipeline_status: 'New',
    discovered_at: '2026-09-01T10:40:00Z',
    latitude: -2.5164,
    longitude: 32.9175,
  },
  {
    place_id: 'node/456789',
    name: 'Green Clinic',
    category: 'clinic',
    website: 'https://greenclinic.co.tz',
    phone: '+255333445566',
    address: 'Medical Plaza, Arusha',
    lead_score: 55,
    priority: 'Medium',
    problems: ['No appointment booking', 'No patient portal'],
    solutions: ['Appointment booking system', 'Patient portal'],
    potential_value: 'Medium',
    total_qualification_score: 48,
    pipeline_status: 'New',
    discovered_at: '2026-09-01T10:45:00Z',
    latitude: -3.3869,
    longitude: 36.6830,
  },
  {
    place_id: 'node/567890',
    name: 'Quick Mart Supermarket',
    category: 'supermarket',
    website: null,
    phone: '+255444556677',
    address: 'Market Street, Dar es Salaam',
    lead_score: 38,
    priority: 'Low',
    problems: ['No website found', 'No inventory system'],
    solutions: ['E-commerce platform', 'Inventory management'],
    potential_value: 'Low',
    total_qualification_score: 30,
    pipeline_status: 'New',
    discovered_at: '2026-09-01T10:50:00Z',
    latitude: -6.8160,
    longitude: 39.2804,
  },
  {
    place_id: 'node/678901',
    name: 'Sunset Bar & Grill',
    category: 'bar',
    website: 'https://sunsetbar.co.tz',
    phone: '+255555667788',
    address: 'Harbor View, Dar es Salaam',
    lead_score: 65,
    priority: 'Medium',
    problems: ['No online menu', 'No reservation system'],
    solutions: ['Digital menu platform', 'Table reservation system'],
    potential_value: 'Medium',
    total_qualification_score: 58,
    pipeline_status: 'Contacted',
    discovered_at: '2026-09-01T10:55:00Z',
    latitude: -6.8235,
    longitude: 39.2680,
  },
  {
    place_id: 'node/789012',
    name: 'Arusha Real Estate Co',
    category: 'real estate',
    website: 'https://arusharealestate.co.tz',
    phone: '+255666778899',
    address: 'City Center, Arusha',
    lead_score: 80,
    priority: 'High',
    problems: ['No property listing platform', 'No virtual tours', 'No inquiry management'],
    solutions: ['Property listing website', 'Virtual tour integration', 'Contact management system'],
    potential_value: 'High',
    total_qualification_score: 75,
    pipeline_status: 'Proposal Sent',
    discovered_at: '2026-09-01T11:00:00Z',
    latitude: -3.3869,
    longitude: 36.6830,
  },
  {
    place_id: 'node/890123',
    name: 'FitLife Gym',
    category: 'gym',
    website: 'https://fitlife.co.tz',
    phone: '+255777889900',
    address: 'Gym Plaza, Mwanza',
    lead_score: 48,
    priority: 'Medium',
    problems: ['No member management system', 'No class booking'],
    solutions: ['Member management platform', 'Class scheduling system'],
    potential_value: 'Medium',
    total_qualification_score: 42,
    pipeline_status: 'New',
    discovered_at: '2026-09-01T11:05:00Z',
    latitude: -2.5164,
    longitude: 32.9175,
  },
  {
    place_id: 'node/901234',
    name: 'Bella Bakery',
    category: 'bakery',
    website: null,
    phone: '+255888990011',
    address: 'Baker Street, Dar es Salaam',
    lead_score: 42,
    priority: 'Medium',
    problems: ['No website found', 'No online ordering'],
    solutions: ['Website with online ordering', 'WhatsApp integration'],
    potential_value: 'Medium',
    total_qualification_score: 38,
    pipeline_status: 'New',
    discovered_at: '2026-09-01T11:10:00Z',
    latitude: -6.8000,
    longitude: 39.2500,
  },
  {
    place_id: 'node/112233',
    name: 'Mzuzu Hospital',
    category: 'hospital',
    website: 'https://mzuzuhospital.co.tz',
    phone: '+255999001122',
    address: 'Hospital Road, Mwanza',
    lead_score: 88,
    priority: 'High',
    problems: ['No patient portal', 'No appointment system', 'No medical records digital', 'No telemedicine'],
    solutions: ['Hospital management system', 'Patient portal', 'Appointment booking', 'Telemedicine platform'],
    potential_value: 'High',
    total_qualification_score: 85,
    pipeline_status: 'Won',
    discovered_at: '2026-08-28T09:00:00Z',
    latitude: -2.5200,
    longitude: 32.9200,
  },
  {
    place_id: 'node/223344',
    name: 'Style Lounge Salon',
    category: 'salon',
    website: 'https://stylelounge.co.tz',
    phone: '+255110022334',
    address: 'Salon Avenue, Dar es Salaam',
    lead_score: 35,
    priority: 'Low',
    problems: ['No booking system'],
    solutions: ['Appointment booking platform'],
    potential_value: 'Low',
    total_qualification_score: 28,
    pipeline_status: 'Not Interested',
    discovered_at: '2026-08-25T14:00:00Z',
    latitude: -6.7900,
    longitude: 39.2100,
  },
  {
    place_id: 'node/334455',
    name: 'TechHub Electronics',
    category: 'electronics store',
    website: 'https://techhub.co.tz',
    phone: '+255220033445',
    address: 'Tech District, Dar es Salaam',
    lead_score: 62,
    priority: 'Medium',
    problems: ['No e-commerce platform', 'No inventory tracking'],
    solutions: ['E-commerce website', 'Inventory management system'],
    potential_value: 'Medium',
    total_qualification_score: 55,
    pipeline_status: 'Contacted',
    discovered_at: '2026-08-30T10:00:00Z',
    latitude: -6.8100,
    longitude: 39.2600,
  },
];

export const mockLeadDetails: Record<string, LeadDetail> = {
  'node/123456': {
    business: {
      place_id: 'node/123456',
      name: 'Cafe Mocha',
      category: 'restaurant',
      website: 'https://cafemocha.com',
      phone: '+255123456789',
      address: '123 Main St, Dar es Salaam',
      latitude: -6.7924,
      longitude: 39.2083,
      rating: 4.2,
      rating_count: 87,
      social_links: ['facebook.com/cafemocha'],
      source: 'openstreetmap',
      discovered_at: '2026-09-01T10:30:00Z',
    },
    research: {
      website: {
        has_website: true,
        reachable: true,
        is_mobile_friendly: false,
        has_ssl: true,
        title: 'Cafe Mocha Dar es Salaam',
        signals_found: ['online_menu', 'contact_form'],
        signals_missing: ['online_ordering', 'online_booking', 'whatsapp_link'],
        social_links: ['facebook.com/cafemocha'],
        notes: ['Website loads slowly on mobile', 'Menu is PDF-only, not interactive'],
      },
      social: {
        platforms_found: ['facebook'],
        platforms_missing: ['instagram', 'twitter_x', 'tiktok'],
        notes: ['Facebook page has 1.2k followers but no recent posts'],
      },
      reachability: {
        email_found: 'info@cafemocha.com',
        contactable_channels: ['email', 'facebook'],
        reachability_score: 40,
      },
    },
    problems: ['No online ordering capability', 'Website not mobile-friendly', 'No active social media presence'],
    solutions: ['Online ordering platform', 'Mobile website redesign', 'Social media management dashboard'],
    potential_value: 'High',
    lead_score: 72,
    priority: 'High',
    score_reasons: [
      'No online ordering',
      'Website is not mobile-friendly',
      'No active social media presence detected',
      'Established business (phone + address on record)',
      'LLM-estimated potential value: High',
    ],
    qualification: {
      business_activity_score: 20,
      digital_presence_score: -10,
      ability_to_pay_score: 15,
      solution_need_score: 35,
      total_score: 68,
      priority: 'High',
      reasoning: [
        'Active business (phone + website/social found)',
        'Weak digital presence',
        'Appears able to invest in solutions',
        'Critical need for software solutions',
      ],
    },
  },
  'node/234567': {
    business: {
      place_id: 'node/234567',
      name: 'Hotel Palm Resort',
      category: 'hotel',
      website: 'https://hotelpalm.co.tz',
      phone: '+255765432100',
      address: 'Beach Road, Dar es Salaam',
      latitude: -6.7749,
      longitude: 39.2244,
      rating: 4.5,
      rating_count: 234,
      social_links: ['facebook.com/hotelpalm', 'instagram.com/hotelpalm'],
      source: 'openstreetmap',
      discovered_at: '2026-09-01T10:35:00Z',
    },
    research: {
      website: {
        has_website: true,
        reachable: true,
        is_mobile_friendly: false,
        has_ssl: true,
        title: 'Hotel Palm Resort - Dar es Salaam',
        signals_found: ['photo_gallery', 'contact_form'],
        signals_missing: ['online_booking', 'whatsapp_link', 'review_integration'],
        social_links: ['facebook.com/hotelpalm', 'instagram.com/hotelpalm'],
        notes: ['Website design is outdated (2018 era)', 'No booking functionality'],
      },
      social: {
        platforms_found: ['facebook', 'instagram'],
        platforms_missing: ['twitter_x', 'tiktok'],
        notes: ['Instagram has 5.6k followers, regular posts'],
      },
      reachability: {
        email_found: 'reservations@hotelpalm.co.tz',
        contactable_channels: ['email', 'facebook', 'instagram'],
        reachability_score: 60,
      },
    },
    problems: ['No online booking system', 'No review management', 'Outdated website design'],
    solutions: ['Hotel booking platform', 'Review management dashboard', 'Website modernization'],
    potential_value: 'High',
    lead_score: 85,
    priority: 'High',
    score_reasons: [
      'No online booking',
      'Website is not mobile-friendly',
      'Established business (phone + address + rating on record)',
      'LLM-estimated potential value: High',
    ],
    qualification: {
      business_activity_score: 20,
      digital_presence_score: -10,
      ability_to_pay_score: 30,
      solution_need_score: 35,
      total_score: 82,
      priority: 'High',
      reasoning: [
        'Active business (phone + website/social found)',
        'Weak digital presence',
        'High ability to pay (hotel + phone + website)',
        'Critical need for software solutions',
      ],
    },
  },
  'node/345678': {
    business: {
      place_id: 'node/345678',
      name: 'City Secondary School',
      category: 'school',
      website: null,
      phone: '+255222334455',
      address: 'Education District, Mwanza',
      latitude: -2.5164,
      longitude: 32.9175,
      rating: null,
      rating_count: null,
      social_links: [],
      source: 'openstreetmap',
      discovered_at: '2026-09-01T10:40:00Z',
    },
    research: {
      website: {
        has_website: false,
        reachable: false,
        is_mobile_friendly: null,
        has_ssl: null,
        title: null,
        signals_found: [],
        signals_missing: ['website', 'online_menu', 'online_ordering', 'online_booking', 'whatsapp_link'],
        social_links: [],
        notes: ['No web presence found at all'],
      },
      social: {
        platforms_found: [],
        platforms_missing: ['facebook', 'instagram', 'twitter_x', 'tiktok'],
        notes: ['No social media presence detected'],
      },
      reachability: {
        email_found: null,
        contactable_channels: ['phone'],
        reachability_score: 20,
      },
    },
    problems: ['No website found', 'No student portal', 'No fee payment system', 'No social media presence'],
    solutions: ['School management platform', 'Student portal', 'Online fee payment system'],
    potential_value: 'High',
    lead_score: 78,
    priority: 'High',
    score_reasons: [
      'No website found',
      'No active social media presence detected',
      'Established business (phone + address on record)',
      'LLM-estimated potential value: High',
    ],
    qualification: {
      business_activity_score: 20,
      digital_presence_score: -10,
      ability_to_pay_score: 30,
      solution_need_score: 35,
      total_score: 71,
      priority: 'High',
      reasoning: [
        'Active business (phone found)',
        'No digital presence',
        'High ability to pay (school + phone)',
        'Critical need for software solutions',
      ],
    },
  },
  'node/789012': {
    business: {
      place_id: 'node/789012',
      name: 'Arusha Real Estate Co',
      category: 'real estate',
      website: 'https://arusharealestate.co.tz',
      phone: '+255666778899',
      address: 'City Center, Arusha',
      latitude: -3.3869,
      longitude: 36.6830,
      rating: 4.0,
      rating_count: 45,
      social_links: ['facebook.com/arusharealestate'],
      source: 'openstreetmap',
      discovered_at: '2026-09-01T11:00:00Z',
    },
    research: {
      website: {
        has_website: true,
        reachable: true,
        is_mobile_friendly: true,
        has_ssl: true,
        title: 'Arusha Real Estate Co - Properties in Arusha',
        signals_found: ['property_listings', 'contact_form'],
        signals_missing: ['virtual_tours', 'mortgage_calculator', 'property_alerts'],
        social_links: ['facebook.com/arusharealestate'],
        notes: ['Listings are text-only, no images or tours'],
      },
      social: {
        platforms_found: ['facebook'],
        platforms_missing: ['instagram', 'twitter_x', 'tiktok'],
        notes: ['Facebook page has 3.4k followers'],
      },
      reachability: {
        email_found: 'info@arusharealestate.co.tz',
        contactable_channels: ['email', 'facebook', 'phone'],
        reachability_score: 60,
      },
    },
    problems: ['No property listing platform with images', 'No virtual tours', 'No inquiry management system'],
    solutions: ['Property listing website with photos', 'Virtual tour integration', 'Contact management system'],
    potential_value: 'High',
    lead_score: 80,
    priority: 'High',
    score_reasons: [
      'Missing online booking',
      'No active social media presence detected',
      'Established business (phone + address + website + rating)',
      'LLM-estimated potential value: High',
    ],
    qualification: {
      business_activity_score: 20,
      digital_presence_score: 15,
      ability_to_pay_score: 30,
      solution_need_score: 35,
      total_score: 75,
      priority: 'High',
      reasoning: [
        'Active business (phone + website + social)',
        'Strong digital presence (website + mobile + social)',
        'High ability to pay (real estate + phone + website)',
        'Critical need for software solutions',
      ],
    },
  },
  'node/112233': {
    business: {
      place_id: 'node/112233',
      name: 'Mzuzu Hospital',
      category: 'hospital',
      website: 'https://mzuzuhospital.co.tz',
      phone: '+255999001122',
      address: 'Hospital Road, Mwanza',
      latitude: -2.5200,
      longitude: 32.9200,
      rating: 3.8,
      rating_count: 156,
      social_links: ['facebook.com/mzuzuhospital'],
      source: 'openstreetmap',
      discovered_at: '2026-08-28T09:00:00Z',
    },
    research: {
      website: {
        has_website: true,
        reachable: true,
        is_mobile_friendly: false,
        has_ssl: true,
        title: 'Mzuzu Hospital - Quality Healthcare',
        signals_found: ['contact_form', 'staff_directory'],
        signals_missing: ['online_booking', 'patient_portal', 'telemedicine', 'lab_results'],
        social_links: ['facebook.com/mzuzuhospital'],
        notes: ['Website is informational only, no interactive features'],
      },
      social: {
        platforms_found: ['facebook'],
        platforms_missing: ['instagram', 'twitter_x', 'tiktok'],
        notes: ['Facebook page has 8.9k followers'],
      },
      reachability: {
        email_found: 'admin@mzuzuhospital.co.tz',
        contactable_channels: ['email', 'facebook', 'phone'],
        reachability_score: 60,
      },
    },
    problems: ['No patient portal', 'No appointment booking system', 'No digital medical records', 'No telemedicine capability'],
    solutions: ['Hospital management system', 'Patient portal', 'Appointment booking platform', 'Telemedicine solution'],
    potential_value: 'High',
    lead_score: 88,
    priority: 'High',
    score_reasons: [
      'No online booking',
      'Website is not mobile-friendly',
      'No active social media presence detected',
      'Established business (phone + address + website + rating)',
      'LLM-estimated potential value: High',
    ],
    qualification: {
      business_activity_score: 20,
      digital_presence_score: -10,
      ability_to_pay_score: 30,
      solution_need_score: 35,
      total_score: 85,
      priority: 'High',
      reasoning: [
        'Active business (phone + website + social)',
        'Weak digital presence',
        'High ability to pay (hospital + phone + website)',
        'Critical need for software solutions',
      ],
    },
  },
};

export const mockProposals: ProposalDocument[] = [
  {
    id: 1,
    place_id: 'node/123456',
    business_name: 'Cafe Mocha',
    package_name: 'Restaurant Digital Platform',
    executive_summary: 'Cafe Mocha has an established presence but lacks critical digital infrastructure. This proposal outlines a comprehensive digital platform including online ordering, mobile-optimized website, and WhatsApp integration to drive revenue and improve customer experience.',
    identified_challenges: [
      'No online ordering capability — customers cannot place orders digitally',
      'Website is not mobile-friendly — 70% of visitors are on mobile',
      'No WhatsApp integration — primary communication channel in Tanzania',
      'Menu is PDF-only, not interactive or searchable',
    ],
    features: ['Responsive Website', 'Digital Menu', 'Online Ordering System', 'WhatsApp Integration', 'Customer Analytics Dashboard'],
    tech_stack: {
      frontend: 'React',
      backend: 'FastAPI',
      database: 'PostgreSQL',
      hosting: 'DigitalOcean',
      reasoning: 'React for interactive UI, FastAPI for fast API development, PostgreSQL for reliability, DigitalOcean for cost-effective hosting in the region.',
    },
    cost_min: 1800,
    cost_max: 3000,
    weeks_min: 4,
    weeks_max: 6,
    expected_benefits: [
      'Increase order volume by 30-50% through digital channels',
      'Improve customer satisfaction with mobile-friendly experience',
      'Reduce phone order overhead with self-service ordering',
      'Gain insights into customer behavior and preferences',
    ],
    status: 'Draft',
    pdf_path: '/data/proposals/cafe_mocha.pdf',
    created_at: '2026-09-01T11:00:00Z',
  },
  {
    id: 2,
    place_id: 'node/234567',
    business_name: 'Hotel Palm Resort',
    package_name: 'Hotel Digital Presence Platform',
    executive_summary: 'Hotel Palm Resort is a well-rated establishment with strong social following but lacks a modern booking system. This proposal delivers a complete digital transformation including online booking, review management, and website modernization.',
    identified_challenges: [
      'No online booking system — losing direct bookings to OTAs',
      'Website design is outdated, not mobile-friendly',
      'No review management — negative reviews go unaddressed',
      'No WhatsApp booking for local customers',
    ],
    features: ['Modern Responsive Website', 'Online Booking Engine', 'Room Management Dashboard', 'WhatsApp Booking Integration', 'Review Management Dashboard', 'Customer CRM'],
    tech_stack: {
      frontend: 'React',
      backend: 'FastAPI',
      database: 'PostgreSQL',
      hosting: 'DigitalOcean',
      reasoning: 'React for dynamic booking interface, FastAPI for real-time availability, PostgreSQL for transactional integrity, DigitalOcean for regional performance.',
    },
    cost_min: 2800,
    cost_max: 5600,
    weeks_min: 5,
    weeks_max: 8,
    expected_benefits: [
      'Reduce OTA commission by 15-25% through direct bookings',
      'Improve booking conversion with modern mobile-first design',
      'Increase positive reviews through proactive management',
      'Build customer loyalty with CRM and repeat guest programs',
    ],
    status: 'Draft',
    pdf_path: '/data/proposals/hotel_palm.pdf',
    created_at: '2026-09-01T11:10:00Z',
  },
  {
    id: 3,
    place_id: 'node/345678',
    business_name: 'City Secondary School',
    package_name: 'School Management Platform',
    executive_summary: 'City Secondary School has no digital presence at all. This proposal delivers a comprehensive school management platform with student portal, fee payment, and parent-teacher communication.',
    identified_challenges: [
      'No website — parents cannot find information online',
      'No student portal — grades and attendance are paper-based',
      'No fee payment system — collections are manual and slow',
      'No parent-teacher communication channel',
    ],
    features: ['School Website', 'Student Portal', 'Online Fee Payment System', 'Result/Grade Portal', 'Parent-Teacher Communication', 'Timetable Management'],
    tech_stack: {
      frontend: 'React',
      backend: 'Django',
      database: 'PostgreSQL',
      hosting: 'DigitalOcean',
      reasoning: 'React for student portal UX, Django for built-in admin and auth, PostgreSQL for data integrity, DigitalOcean for cost control.',
    },
    cost_min: 2800,
    cost_max: 5600,
    weeks_min: 5,
    weeks_max: 9,
    expected_benefits: [
      'Reduce fee collection time by 60% with online payments',
      'Improve parent satisfaction with real-time access to grades',
      'Reduce administrative overhead with digital processes',
      'Enhance school reputation with professional web presence',
    ],
    status: 'Draft',
    pdf_path: '/data/proposals/city_school.pdf',
    created_at: '2026-09-01T11:15:00Z',
  },
  {
    id: 4,
    place_id: 'node/789012',
    business_name: 'Arusha Real Estate Co',
    package_name: 'Real Estate Digital Platform',
    executive_summary: 'Arusha Real Estate Co has a basic website but lacks key features that modern property buyers expect. This proposal delivers a full property platform with virtual tours, inquiry management, and property alerts.',
    identified_challenges: [
      'No property listing platform with quality photos',
      'No virtual tours — buyers must visit in person',
      'No inquiry management — leads are lost',
      'No property alerts — buyers miss new listings',
    ],
    features: ['Property Listing Website', 'Virtual Tour Integration', 'Contact/Inquiry Management', 'Property Alert System', 'Agent Profiles', 'Mortgage Calculator'],
    tech_stack: {
      frontend: 'Next.js',
      backend: 'Node/Express',
      database: 'MongoDB',
      hosting: 'Render',
      reasoning: 'Next.js for SEO and SSR, Node/Express for flexible API, MongoDB for flexible property data, Render for easy deployment.',
    },
    cost_min: 2000,
    cost_max: 4900,
    weeks_min: 4,
    weeks_max: 7,
    expected_benefits: [
      'Increase qualified inquiries by 40-60%',
      'Reduce time-to-close with virtual tours',
      'Improve agent productivity with inquiry management',
      'Build buyer loyalty with property alerts',
    ],
    status: 'Draft',
    pdf_path: '/data/proposals/arusha_realestate.pdf',
    created_at: '2026-09-01T11:20:00Z',
  },
  {
    id: 5,
    place_id: 'node/112233',
    business_name: 'Mzuzu Hospital',
    package_name: 'Hospital Management System',
    executive_summary: 'Mzuzu Hospital serves thousands of patients but operates without digital infrastructure. This proposal delivers a comprehensive hospital management system with patient portal, appointment booking, and telemedicine.',
    identified_challenges: [
      'No patient portal — patients have no digital access',
      'No appointment booking — phone-only scheduling',
      'No digital medical records — paper-based system',
      'No telemedicine — rural patients cannot access care remotely',
    ],
    features: ['Hospital Website', 'Patient Portal', 'Appointment Booking System', 'Electronic Medical Records', 'Telemedicine Platform', 'Lab Results Portal', 'Pharmacy Integration'],
    tech_stack: {
      frontend: 'React',
      backend: 'FastAPI',
      database: 'PostgreSQL',
      hosting: 'DigitalOcean',
      reasoning: 'React for patient-facing UX, FastAPI for HIPAA-compliant APIs, PostgreSQL for medical data integrity, DigitalOcean for regional data residency.',
    },
    cost_min: 4200,
    cost_max: 8400,
    weeks_min: 6,
    weeks_max: 10,
    expected_benefits: [
      'Reduce appointment no-shows by 35% with digital booking',
      'Improve patient outcomes with accessible medical records',
      'Extend reach to rural patients with telemedicine',
      'Reduce administrative costs by 40% with digital processes',
    ],
    status: 'Draft',
    pdf_path: '/data/proposals/mzuzu_hospital.pdf',
    created_at: '2026-08-28T10:00:00Z',
  },
];

export const mockDrafts: OutreachDraft[] = [
  {
    id: 7,
    place_id: 'node/123456',
    business_name: 'Cafe Mocha',
    channel: 'email',
    subject: 'Digital ordering for Cafe Mocha',
    personalization_hook: 'I noticed Cafe Mocha doesn\'t have online ordering — many of your customers are probably looking for it on your website.',
    body: 'Hi,\n\nI noticed that Cafe Mocha doesn\'t currently have online ordering. With more customers expecting to order ahead, this could be a simple way to increase your daily orders.\n\nI help local restaurants like yours set up digital ordering platforms that integrate with your existing website. For Cafe Mocha, I\'d recommend:\n\n- An online ordering system that works on mobile\n- WhatsApp integration for direct customer orders\n- A digital menu that\'s easy to update\n\nThe whole setup typically takes 4-6 weeks and starts at $1,800. I\'d be happy to show you a demo of what this could look like for Cafe Mocha.\n\nWould you be open to a quick call this week?\n\nBest regards',
    status: 'Pending Approval',
    created_at: '2026-09-01T12:00:00Z',
    approved_at: null,
    sent_at: null,
  },
  {
    id: 6,
    place_id: 'node/234567',
    business_name: 'Hotel Palm Resort',
    channel: 'whatsapp',
    subject: null,
    personalization_hook: 'I saw your Instagram — great photos! But noticed guests can\'t book directly on your website.',
    body: 'Hi! I saw your Instagram page — great photos of the resort. I noticed though that guests can\'t book directly through your website, which means you\'re probably losing some bookings to OTA platforms.\n\nI help hotels like yours set up direct booking systems. For Hotel Palm Resort, I\'d suggest:\n\n- An online booking engine on your website\n- WhatsApp booking for local guests\n- A modern mobile-friendly website redesign\n\nThis typically saves hotels 15-25% in OTA commissions. Would you like to learn more?',
    status: 'Pending Approval',
    created_at: '2026-09-01T12:05:00Z',
    approved_at: null,
    sent_at: null,
  },
  {
    id: 5,
    place_id: 'node/345678',
    business_name: 'City Secondary School',
    channel: 'linkedin',
    subject: null,
    personalization_hook: 'I noticed City Secondary School doesn\'t have a website — parents are likely searching for school info online.',
    body: 'Hello, I noticed that City Secondary School doesn\'t have a website. Many parents now search for school information online before enrolling their children. I help schools build digital platforms that include student portals, online fee payments, and parent-teacher communication tools. Would you be interested in a brief conversation about how this could work for your school?',
    status: 'Pending Approval',
    created_at: '2026-09-01T12:10:00Z',
    approved_at: null,
    sent_at: null,
  },
  {
    id: 4,
    place_id: 'node/789012',
    business_name: 'Arusha Real Estate Co',
    channel: 'email',
    subject: 'Better property listings for Arusha Real Estate',
    personalization_hook: 'I was browsing your listings and noticed they\'re text-only — adding photos and virtual tours could significantly increase inquiries.',
    body: 'Hi,\n\nI was browsing your property listings on arusharealestate.co.tz and noticed they\'re currently text-only. In my experience, adding quality photos and virtual tours can increase qualified inquiries by 40-60%.\n\nI build digital platforms for real estate companies that include:\n\n- Property listings with photo galleries and virtual tours\n- Inquiry management so no lead falls through the cracks\n- Property alerts so buyers know about new listings immediately\n- A modern, mobile-friendly website redesign\n\nThis typically takes 4-7 weeks and starts at $2,000. I\'d love to show you what this could look like for Arusha Real Estate.\n\nWould you be open to a quick call?\n\nBest regards',
    status: 'Approved',
    created_at: '2026-09-01T12:15:00Z',
    approved_at: '2026-09-01T14:00:00Z',
    sent_at: null,
  },
  {
    id: 3,
    place_id: 'node/678901',
    business_name: 'Sunset Bar & Grill',
    channel: 'email',
    subject: 'Digital menu and reservations for Sunset Bar',
    personalization_hook: 'I saw your bar has great reviews but no online menu or reservation system — adding those could fill more tables.',
    body: 'Hi,\n\nI saw that Sunset Bar & Grill has great reviews but no online menu or reservation system. Adding those could help fill more tables, especially from customers who discover you online.\n\nI build digital platforms for bars and restaurants that include:\n\n- A digital menu that\'s easy to update\n- An online reservation system\n- A mobile-friendly website\n- WhatsApp integration for bookings\n\nThis typically takes 3-5 weeks and starts at $1,500. I\'d be happy to show you a demo.\n\nWould you be open to a quick call?\n\nBest regards',
    status: 'Sent',
    created_at: '2026-08-30T12:00:00Z',
    approved_at: '2026-08-30T14:00:00Z',
    sent_at: '2026-08-30T16:00:00Z',
  },
  {
    id: 2,
    place_id: 'node/112233',
    business_name: 'Mzuzu Hospital',
    channel: 'email',
    subject: 'Digital patient management for Mzuzu Hospital',
    personalization_hook: 'I noticed Mzuzu Hospital\'s website is informational only — adding a patient portal and appointment booking could transform patient experience.',
    body: 'Dear Administration,\n\nI noticed that Mzuzu Hospital\'s website is informational only. Adding a patient portal and online appointment booking could significantly improve patient experience and reduce administrative overhead.\n\nI build hospital management systems that include:\n\n- Patient portal with access to medical records\n- Online appointment booking\n- Telemedicine for remote patients\n- Lab results portal\n- Pharmacy integration\n\nThis typically takes 6-10 weeks. I\'d be happy to discuss how this could work for Mzuzu Hospital.\n\nWould you be available for a meeting?\n\nBest regards',
    status: 'Sent',
    created_at: '2026-08-28T12:00:00Z',
    approved_at: '2026-08-28T14:00:00Z',
    sent_at: '2026-08-28T16:00:00Z',
  },
  {
    id: 1,
    place_id: 'node/334455',
    business_name: 'TechHub Electronics',
    channel: 'whatsapp',
    subject: null,
    personalization_hook: 'I noticed you don\'t have an online store — with electronics, many customers want to browse and compare online first.',
    body: 'Hi! I noticed TechHub Electronics doesn\'t have an online store. For electronics, many customers want to browse and compare products online before visiting. I build e-commerce platforms with inventory management that could help you reach more customers. Would you like to learn more?',
    status: 'Rejected',
    created_at: '2026-08-29T10:00:00Z',
    approved_at: null,
    sent_at: null,
  },
];

export const mockResponses: ResponseRecord[] = [
  {
    id: 1,
    place_id: 'node/112233',
    outreach_draft_id: 2,
    response_text: 'We are interested in your proposal. Can we schedule a call next week to discuss the details? We have been looking into digitizing our patient records and your platform seems like a good fit.',
    classified_status: 'Converted',
    analyzed_at: '2026-08-29T10:00:00Z',
  },
  {
    id: 2,
    place_id: 'node/678901',
    outreach_draft_id: 3,
    response_text: 'Thanks for reaching out. We\'re interested but need to think about the budget. Can you send us more details about the pricing options?',
    classified_status: 'Needs More Info',
    analyzed_at: '2026-08-31T10:00:00Z',
  },
  {
    id: 3,
    place_id: 'node/123456',
    outreach_draft_id: 7,
    response_text: 'This sounds interesting. We\'ve been thinking about adding online ordering. Let\'s talk more about this.',
    classified_status: 'Warm Lead',
    analyzed_at: '2026-09-02T10:00:00Z',
  },
];

export const mockCRMLeads: Record<string, CRMLead> = {
  'node/123456': { place_id: 'node/123456', pipeline_status: 'Contacted', interest_level: 'Medium', last_contact_date: '2026-09-01', next_follow_up_date: '2026-09-08' },
  'node/234567': { place_id: 'node/234567', pipeline_status: 'Warm', interest_level: 'High', last_contact_date: '2026-09-01', next_follow_up_date: '2026-09-08' },
  'node/345678': { place_id: 'node/345678', pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, next_follow_up_date: null },
  'node/456789': { place_id: 'node/456789', pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, next_follow_up_date: null },
  'node/567890': { place_id: 'node/567890', pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, next_follow_up_date: null },
  'node/678901': { place_id: 'node/678901', pipeline_status: 'Contacted', interest_level: 'Medium', last_contact_date: '2026-08-30', next_follow_up_date: '2026-09-06' },
  'node/789012': { place_id: 'node/789012', pipeline_status: 'Proposal Sent', interest_level: 'Unknown', last_contact_date: '2026-09-01', next_follow_up_date: '2026-09-08' },
  'node/890123': { place_id: 'node/890123', pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, next_follow_up_date: null },
  'node/901234': { place_id: 'node/901234', pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, next_follow_up_date: null },
  'node/112233': { place_id: 'node/112233', pipeline_status: 'Won', interest_level: 'High', last_contact_date: '2026-08-28', next_follow_up_date: null },
  'node/223344': { place_id: 'node/223344', pipeline_status: 'Not Interested', interest_level: 'Low', last_contact_date: '2026-08-25', next_follow_up_date: null },
  'node/334455': { place_id: 'node/334455', pipeline_status: 'Contacted', interest_level: 'Low', last_contact_date: '2026-08-30', next_follow_up_date: '2026-09-06' },
};

export const mockFunnelMetrics: FunnelMetrics = {
  businesses_found: 142,
  analyzed: 120,
  qualified: 95,
  proposals_generated: 42,
  outreach_drafted: 38,
  outreach_approved: 25,
  outreach_sent: 20,
  responses_logged: 15,
  interested: 8,
  clients_won: 3,
};

export const mockDashboardLeads: DashboardLeadRow[] = [
  { name: 'Mzuzu Hospital', category: 'hospital', total_score: 85, qual_priority: 'High', proposal_status: 'Generated', cost_min: 4200, cost_max: 8400, weeks_min: 6, weeks_max: 10, package_name: 'Hospital Management System', pipeline_status: 'Won', interest_level: 'High', last_contact_date: '2026-08-28', rank_score: 92 },
  { name: 'Hotel Palm Resort', category: 'hotel', total_score: 82, qual_priority: 'High', proposal_status: 'Generated', cost_min: 2800, cost_max: 5600, weeks_min: 5, weeks_max: 8, package_name: 'Hotel Digital Presence Platform', pipeline_status: 'Warm', interest_level: 'High', last_contact_date: '2026-09-01', rank_score: 88 },
  { name: 'Arusha Real Estate Co', category: 'real estate', total_score: 75, qual_priority: 'High', proposal_status: 'Generated', cost_min: 2000, cost_max: 4900, weeks_min: 4, weeks_max: 7, package_name: 'Real Estate Digital Platform', pipeline_status: 'Proposal Sent', interest_level: 'Unknown', last_contact_date: '2026-09-01', rank_score: 82 },
  { name: 'Cafe Mocha', category: 'restaurant', total_score: 68, qual_priority: 'High', proposal_status: 'Generated', cost_min: 1800, cost_max: 3000, weeks_min: 4, weeks_max: 6, package_name: 'Restaurant Digital Platform', pipeline_status: 'Contacted', interest_level: 'Medium', last_contact_date: '2026-09-01', rank_score: 78 },
  { name: 'City Secondary School', category: 'school', total_score: 71, qual_priority: 'High', proposal_status: 'Generated', cost_min: 2800, cost_max: 5600, weeks_min: 5, weeks_max: 9, package_name: 'School Management Platform', pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, rank_score: 75 },
  { name: 'Sunset Bar & Grill', category: 'bar', total_score: 58, qual_priority: 'Medium', proposal_status: 'Not started', cost_min: null, cost_max: null, weeks_min: null, weeks_max: null, package_name: null, pipeline_status: 'Contacted', interest_level: 'Medium', last_contact_date: '2026-08-30', rank_score: 62 },
  { name: 'TechHub Electronics', category: 'electronics store', total_score: 55, qual_priority: 'Medium', proposal_status: 'Not started', cost_min: null, cost_max: null, weeks_min: null, weeks_max: null, package_name: null, pipeline_status: 'Contacted', interest_level: 'Low', last_contact_date: '2026-08-30', rank_score: 58 },
  { name: 'Green Clinic', category: 'clinic', total_score: 48, qual_priority: 'Medium', proposal_status: 'Not started', cost_min: null, cost_max: null, weeks_min: null, weeks_max: null, package_name: null, pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, rank_score: 50 },
  { name: 'FitLife Gym', category: 'gym', total_score: 42, qual_priority: 'Medium', proposal_status: 'Not started', cost_min: null, cost_max: null, weeks_min: null, weeks_max: null, package_name: null, pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, rank_score: 44 },
  { name: 'Bella Bakery', category: 'bakery', total_score: 38, qual_priority: 'Low', proposal_status: 'Not started', cost_min: null, cost_max: null, weeks_min: null, weeks_max: null, package_name: null, pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, rank_score: 40 },
  { name: 'Quick Mart Supermarket', category: 'supermarket', total_score: 30, qual_priority: 'Low', proposal_status: 'Not started', cost_min: null, cost_max: null, weeks_min: null, weeks_max: null, package_name: null, pipeline_status: 'New', interest_level: 'Unknown', last_contact_date: null, rank_score: 32 },
  { name: 'Style Lounge Salon', category: 'salon', total_score: 28, qual_priority: 'Low', proposal_status: 'Not started', cost_min: null, cost_max: null, weeks_min: null, weeks_max: null, package_name: null, pipeline_status: 'Not Interested', interest_level: 'Low', last_contact_date: '2026-08-25', rank_score: 30 },
];

export const mockFollowUps: FollowUpLead[] = [
  { place_id: 'node/223344', name: 'Style Lounge Salon', category: 'salon', last_contact_date: '2026-08-25', next_follow_up_date: '2026-09-01', days_since_contact: 12 },
  { place_id: 'node/678901', name: 'Sunset Bar & Grill', category: 'bar', last_contact_date: '2026-08-30', next_follow_up_date: '2026-09-06', days_since_contact: 7 },
  { place_id: 'node/334455', name: 'TechHub Electronics', category: 'electronics store', last_contact_date: '2026-08-30', next_follow_up_date: '2026-09-06', days_since_contact: 7 },
];

export const mockInsights: CategoryInsight[] = [
  { category: 'restaurant', total: 45, contacted: 30, replied: 12, converted: 5, conversion_rate: 17, common_package: 'Restaurant Digital Platform' },
  { category: 'hotel', total: 22, contacted: 15, replied: 8, converted: 3, conversion_rate: 20, common_package: 'Hotel Digital Presence Platform' },
  { category: 'school', total: 18, contacted: 12, replied: 6, converted: 2, conversion_rate: 17, common_package: 'School Management Platform' },
  { category: 'hospital', total: 8, contacted: 4, replied: 2, converted: 1, conversion_rate: 25, common_package: 'Hospital Management System' },
  { category: 'real estate', total: 15, contacted: 8, replied: 4, converted: 2, conversion_rate: 25, common_package: 'Real Estate Digital Platform' },
  { category: 'clinic', total: 12, contacted: 5, replied: 1, converted: 0, conversion_rate: 0, common_package: null },
];

export const mockModelStatus: ModelStatus[] = [
  { name: 'qwen2.5:3b', size: 2147483648, size_vram: 2147483648, expires_at: '2026-09-06T12:35:00Z' },
  { name: 'qwen2.5:7b', size: 4939253760, size_vram: 4939253760, expires_at: '2026-09-06T12:30:00Z' },
];

export const mockDiscoveryReports: DiscoveryReport[] = [
  { business_name: 'Cafe Mocha', category: 'restaurant', lead_score: 72, priority: 'High', problems: ['No online ordering', 'Website not mobile-friendly'], solutions: ['Online ordering platform', 'Mobile redesign'], potential_value: 'High' },
  { business_name: 'Hotel Palm Resort', category: 'hotel', lead_score: 85, priority: 'High', problems: ['No online booking', 'Outdated website'], solutions: ['Booking platform', 'Website modernization'], potential_value: 'High' },
  { business_name: 'City Secondary School', category: 'school', lead_score: 78, priority: 'High', problems: ['No website', 'No student portal'], solutions: ['School management platform', 'Student portal'], potential_value: 'High' },
  { business_name: 'Green Clinic', category: 'clinic', lead_score: 55, priority: 'Medium', problems: ['No appointment booking'], solutions: ['Booking system', 'Patient portal'], potential_value: 'Medium' },
  { business_name: 'Quick Mart', category: 'supermarket', lead_score: 38, priority: 'Low', problems: ['No website'], solutions: ['E-commerce platform'], potential_value: 'Low' },
  { business_name: 'Sunset Bar', category: 'bar', lead_score: 65, priority: 'Medium', problems: ['No online menu'], solutions: ['Digital menu', 'Reservation system'], potential_value: 'Medium' },
  { business_name: 'Arusha Real Estate', category: 'real estate', lead_score: 80, priority: 'High', problems: ['No virtual tours', 'No inquiry management'], solutions: ['Property platform', 'Virtual tours'], potential_value: 'High' },
  { business_name: 'FitLife Gym', category: 'gym', lead_score: 48, priority: 'Medium', problems: ['No member system'], solutions: ['Member management'], potential_value: 'Medium' },
  { business_name: 'Bella Bakery', category: 'bakery', lead_score: 42, priority: 'Medium', problems: ['No website', 'No online ordering'], solutions: ['Website with ordering'], potential_value: 'Medium' },
  { business_name: 'Mzuzu Hospital', category: 'hospital', lead_score: 88, priority: 'High', problems: ['No patient portal', 'No appointment system'], solutions: ['Hospital management system'], potential_value: 'High' },
];
